### ISSUE TITLE
Middleware not loading automatically

### ISSUE THREAD

**Issue by SebFourault** [botpress/botpress-api.ai#3]
Hello 

I installed the API.ai middleware via the graphic interface.
But when I launch Botpress (botpress start) the middleware is not launched 

My logs : 
14:38:54 - info: Starting botpress version 0.1.7
14:38:55 - info: Loaded 4 modules
14:38:55 - debug: Loading middleware: analytics.incoming
14:38:55 - debug: Loading middleware: analytics.outgoing
14:38:55 - debug: Loading middleware: hear
14:38:55 - debug: Loading middleware: messenger.sendMessages
14:38:55 - info: Bot launched. Visit: http://localhost:3000

And then, when I change the order of the middlewares in the graphic interface, and click "Save", it finally loads api.ai : 

14:41:39 - debug: Loading middleware: analytics.incoming
14:41:39 - debug: Loading middleware: analytics.outgoing
**14:41:39 - debug: Loading middleware: apiai.incoming**
14:41:39 - debug: Loading middleware: hear
14:41:39 - debug: Loading middleware: messenger.sendMessages

Is it a bug or should I include a specific command (other than bp.middlewares.load() ) ?

Thanks a lot :)

**Comment by slvnperron** [comment]
Hey!

I just fixed that issue now, please update API.AI module to `2.0.6`

Many thanks for reporting this issue :)

PS: love your github username ;)

**Comment by SebFourault** [comment]
Thanks a lot ! :smiley: 
I :heart: botpress so far, you guyz did an amazing job ;)

**Comment by slvnperron** [comment]
Thanks! Really appreciate hearing that 😃
