### ISSUE TITLE
Module not found on Botpress 1.0.5

### ISSUE THREAD

**Issue by rdricco** [botpress/botpress-api.ai#4]
I tried to install via GUI and CLI, on both I got the "The module is not properly registered" on API.AI tab.

**Comment by slvnperron** [comment]
Thanks @rdricco , we fixed this issue in the latest version of Botpress (please update) :)

**Comment by twelvearrays** [comment]
If you change the port for botpress.  ie from 3000 to 3030 via botfile.js.  You will receive the "The module is not properly registered" for API.AI.  Is there a configuration I missing for API.ai?

**Comment by slvnperron** [comment]
@twelvearrays I can't replicate this one, have you tried force refreshing the page?

**Comment by twelvearrays** [comment]
I can't repeat it either. 👎  Seemed more to do with upgrading from 1.0.5 to 1.0.9.  Working as expected now.  Thanks!
